### ISSUE TITLE
some questions about ctc_decoder

### ISSUE THREAD

**Issue by shengyudingli** [houkai/caffe#1]
I'm sorry to bother you, can you give some usages (for example, the net prototxt file ) about CTC? I found that you changed the decode portion, is there any problems in the previous edition ? Thank you for any suggestion.

**Comment by houkai** [comment]
https://gist.github.com/houkai/a795e2e2f095ba50d0b95f2a5b727f9b
https://www.cnblogs.com/houkai/p/6261631.html
Here is one example, but this CTC of caffe version is no longer practical. At least I've switched to tensorflow, there is many examples of TF in github.
